# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'TVPlay-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVPlay-iOS
   pod 'MobileVLCKit', '~>3.3.0'
end
