# Uncomment the next line to define a global platform for your project
platform :macos, '10.9'

target 'TVPlay' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for TVPlay
  pod 'VLCKit', '~>3.3.0'
end
